# Generated by Django 4.1.2 on 2022-10-10 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_business_student_user_type"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Business",
        ),
        migrations.DeleteModel(
            name="Student",
        ),
        migrations.AlterField(
            model_name="user",
            name="type",
            field=models.CharField(
                choices=[
                    ("APPROVED_BUSINESS", "Approved Business"),
                    ("BUSINESS", "Business"),
                    ("STUDENT", "Student"),
                ],
                default="STUDENT",
                max_length=20,
            ),
        ),
    ]
